version: 2
jobs:
  build:
    docker:
      - image: relastle/pmy:0.1.0
    steps:
      - checkout
      - run: echo "A first hello"

workflows:
  version: 2
  deploy:
    jobs:
      - deploy_job:
        filters:
          branches:
            only:
              - develop
